command:
  - bash
  - -c
  - "mkdir -p ~/.local/bin && bash install_micro.sh && mv micro ~/.local/bin/ 2>/dev/null || true && python setup_claude.py && python app.py"
env:
  - name: HOME
    value: /app/python/source_code
  - name: DATABRICKS_HOST
    valueFrom: DATABRICKS_HOST
  - name: DATABRICKS_TOKEN
    valueFrom: DATABRICKS_TOKEN
  - name: ANTHROPIC_MODEL
    value: databricks-claude-sonnet-4-5
